image: docker

services: 
    - docker:dind

stages:
    - deploy

docker_build:
    stage: deploy
    only: 
    - master
    script:     
    - sudo apt install python3-pip
    - pip install docker-compose
    - docker compose up -d --build
    environment: master
