image: docker

services: 
    - docker:dind

stages:
    - deploy


docker_build:
    stage: deploy
    tags:
    - wordpress-01
    only: 
    - master
    script:     
    - sudo apt install -y python3-pip
    - pip install docker-compose
    - docker compose up -d --build
    environment: master
