deploy-job:
  stage: deploy
  only:
    - master
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - docker info
    - docker compose down
    - docker compose build
    - docker compose up -d
  environment: master