deploy-job:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - docker info
    - docker compose down
    - docker compose build
    - docker compose up -d
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH