

services:

  nginx:  
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./wordpress:/var/www/html

  mysql:
    image: mysql:5.7    
    environment:
      MYSQL_ROOT_PASSWORD: 54321
      MYSQL_DATABASE: wordpress
      MYSQL_USER: macgenm
      MYSQL_PASSWORD: 54321

    volumes:
      - ./mysql:/var/lib/mysql


  php:
    
    build:
      context: .
      dockerfile: php.dockerfile
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: macgenm
      WORDPRESS_DB_PASSWORD: 54321
      WORDPRESS_DB_NAME: wordpress
   
   
    volumes:
      - ./wordpress:/var/www/html 




       


  
